import { Post } from './types';

// Helper to generate UUID-like IDs
const id = (prefix: string, n: number) => `${prefix}-${String(n).padStart(4, '0')}-4a3b-8c2d-e1f0a9b8c7d6`;

const now = '2026-04-01T00:00:00.000Z';

export const mockPosts: Post[] = [
  // =============================================
  // SCENARIO 1: Type 2 Diabetes (E11)
  // =============================================
  {
    id: id('post', 1),
    universalTitle: 'Understanding Type 2 Diabetes',
    contentValue: 95,
    category: ['condition_diabetes'],
    topic: ['overview'],
    icd10: ['E11', 'E11.9'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 1),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Understanding Type 2 Diabetes',
      description: 'A comprehensive overview of Type 2 Diabetes — what it is, how it affects your body, and what you can expect on your health journey. This video explains the condition in plain language.',
      keywords: ['diabetes', 'type 2', 'blood sugar', 'insulin resistance'],
      learningOutcome: 'Understand what Type 2 Diabetes is and how it affects the body',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 1),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 1),
      url: 'https://cdn.sanctuaryhealth.io/videos/diabetes-overview.mp4',
      thumbnailUrl: '/thumbnails/diabetes-overview.jpg',
      durationSeconds: 420,
    }],
  },
  {
    id: id('post', 2),
    universalTitle: 'Metformin and Diabetes Medication',
    contentValue: 90,
    category: ['condition_diabetes'],
    topic: ['medication'],
    icd10: ['E11', 'E11.65'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 2),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Your Guide to Metformin',
      description: 'Everything you need to know about Metformin — how it works, when to take it, what to expect in the first few weeks, and tips for managing common side effects.',
      keywords: ['metformin', 'diabetes medication', 'blood sugar control'],
      learningOutcome: 'Understand how Metformin works and how to take it correctly',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 2),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 2),
      url: 'https://cdn.sanctuaryhealth.io/videos/metformin-guide.mp4',
      thumbnailUrl: '/thumbnails/metformin-guide.jpg',
      durationSeconds: 360,
    }],
  },
  {
    id: id('post', 3),
    universalTitle: 'Living Well with Diabetes: Lifestyle Changes',
    contentValue: 88,
    category: ['condition_diabetes', 'wellbeing_nutrition'],
    topic: ['lifestyle'],
    icd10: ['E11'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 3),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Lifestyle Changes That Make a Real Difference',
      description: 'Practical, evidence-based lifestyle changes that can help manage Type 2 Diabetes — from diet adjustments to exercise routines that fit into a busy life.',
      keywords: ['diabetes lifestyle', 'diet', 'exercise', 'blood sugar management'],
      learningOutcome: 'Identify 3-5 lifestyle changes to help manage diabetes',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 3),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 3),
      url: 'https://cdn.sanctuaryhealth.io/articles/diabetes-lifestyle.html',
    }],
  },
  {
    id: id('post', 4),
    universalTitle: 'Recognising Diabetes Symptoms',
    contentValue: 85,
    category: ['condition_diabetes'],
    topic: ['symptoms'],
    icd10: ['E11', 'E11.9'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 4),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Symptoms to Watch For',
      description: 'Learn to recognise the key symptoms of Type 2 Diabetes and when to contact your healthcare provider. Early recognition leads to better management.',
      keywords: ['diabetes symptoms', 'warning signs', 'blood sugar'],
      learningOutcome: 'Recognise key diabetes symptoms and know when to seek help',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 4),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 4),
      url: 'https://cdn.sanctuaryhealth.io/videos/diabetes-symptoms.mp4',
      thumbnailUrl: '/thumbnails/diabetes-symptoms.jpg',
      durationSeconds: 300,
    }],
  },
  {
    id: id('post', 5),
    universalTitle: 'Understanding Diabetes Risks and Complications',
    contentValue: 82,
    category: ['condition_diabetes'],
    topic: ['risks'],
    icd10: ['E11', 'E11.65'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 5),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Risks and Complications You Should Know About',
      description: 'An honest look at the potential complications of Type 2 Diabetes and practical steps you can take to reduce your risk. Knowledge is your best protection.',
      keywords: ['diabetes complications', 'neuropathy', 'retinopathy', 'cardiovascular risk'],
      learningOutcome: 'Understand potential complications and how to reduce risk',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 5),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 5),
      url: 'https://cdn.sanctuaryhealth.io/articles/diabetes-risks.html',
    }],
  },
  {
    id: id('post', 6),
    universalTitle: 'Side Effects of Diabetes Medications',
    contentValue: 87,
    category: ['condition_diabetes'],
    topic: ['sideEffects'],
    icd10: ['E11'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 6),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Managing Medication Side Effects',
      description: 'Common side effects of diabetes medications like Metformin, what is normal in the first few weeks, and when to talk to your doctor about adjustments.',
      keywords: ['metformin side effects', 'nausea', 'GI issues', 'medication adjustment'],
      learningOutcome: 'Know which side effects are normal and when to contact your doctor',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 6),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 6),
      url: 'https://cdn.sanctuaryhealth.io/articles/diabetes-side-effects.html',
    }],
  },
  {
    id: id('post', 7),
    universalTitle: 'What Causes Type 2 Diabetes',
    contentValue: 80,
    category: ['condition_diabetes'],
    topic: ['causes'],
    icd10: ['E11'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 7),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Understanding the Causes of Type 2 Diabetes',
      description: 'Why does Type 2 Diabetes develop? This video explains the role of genetics, lifestyle factors, and insulin resistance in simple terms.',
      keywords: ['diabetes causes', 'insulin resistance', 'genetics', 'risk factors'],
      learningOutcome: 'Understand the key factors that contribute to Type 2 Diabetes',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 7),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 7),
      url: 'https://cdn.sanctuaryhealth.io/videos/diabetes-causes.mp4',
      thumbnailUrl: '/thumbnails/diabetes-causes.jpg',
      durationSeconds: 280,
    }],
  },
  {
    id: id('post', 8),
    universalTitle: 'Diagnosing Type 2 Diabetes',
    contentValue: 78,
    category: ['condition_diabetes'],
    topic: ['diagnosis'],
    icd10: ['E11', 'E11.9'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 8),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'How Type 2 Diabetes Is Diagnosed',
      description: 'Understanding your diagnosis — what the blood tests mean, what HbA1c levels indicate, and what happens after you receive a Type 2 Diabetes diagnosis.',
      keywords: ['diabetes diagnosis', 'HbA1c', 'blood glucose test', 'fasting glucose'],
      learningOutcome: 'Understand the diagnostic tests and what your results mean',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 8),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 8),
      url: 'https://cdn.sanctuaryhealth.io/articles/diabetes-diagnosis.html',
    }],
  },
  {
    id: id('post', 9),
    universalTitle: 'Diabetes Support and Resources',
    contentValue: 75,
    category: ['condition_diabetes', 'wellbeing_mentalHealth'],
    topic: ['support'],
    icd10: ['E11'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 9),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Support Networks and Resources',
      description: 'You are not alone. This guide covers support groups, mental health resources, and practical help available for people living with Type 2 Diabetes.',
      keywords: ['diabetes support', 'mental health', 'support groups', 'coping'],
      learningOutcome: 'Know where to find support and how to access help',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 9),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 9),
      url: 'https://cdn.sanctuaryhealth.io/articles/diabetes-support.html',
    }],
  },
  {
    id: id('post', 10),
    universalTitle: 'Blood Sugar Monitoring at Home',
    contentValue: 86,
    category: ['condition_diabetes'],
    topic: ['lifestyle'],
    icd10: ['E11', 'E11.65'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 10),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'How to Monitor Your Blood Sugar at Home',
      description: 'A step-by-step guide to home blood sugar monitoring — when to test, how to use your meter, what your readings mean, and when to be concerned.',
      keywords: ['blood sugar monitoring', 'glucose meter', 'home testing', 'readings'],
      learningOutcome: 'Confidently monitor blood sugar at home and interpret results',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 10),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 10),
      url: 'https://cdn.sanctuaryhealth.io/videos/blood-sugar-monitoring.mp4',
      thumbnailUrl: '/thumbnails/blood-sugar-monitoring.jpg',
      durationSeconds: 390,
    }],
  },

  // =============================================
  // SCENARIO 2: Hypertension (I10)
  // =============================================
  {
    id: id('post', 11),
    universalTitle: 'Understanding High Blood Pressure',
    contentValue: 93,
    category: ['condition_cardiovascular', 'condition_hypertension'],
    topic: ['overview'],
    icd10: ['I10', 'I11'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 11),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Understanding High Blood Pressure',
      description: 'What high blood pressure means for your health, why it matters, and what you can do about it. A clear, jargon-free explanation of hypertension.',
      keywords: ['hypertension', 'high blood pressure', 'cardiovascular health'],
      learningOutcome: 'Understand what blood pressure numbers mean and why they matter',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 11),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 11),
      url: 'https://cdn.sanctuaryhealth.io/videos/hypertension-overview.mp4',
      thumbnailUrl: '/thumbnails/hypertension-overview.jpg',
      durationSeconds: 350,
    }],
  },
  {
    id: id('post', 12),
    universalTitle: 'Blood Pressure Medications Explained',
    contentValue: 89,
    category: ['condition_cardiovascular', 'condition_hypertension'],
    topic: ['medication'],
    icd10: ['I10', 'I11'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 12),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Your Blood Pressure Medication Guide',
      description: 'A guide to common blood pressure medications — ACE inhibitors, beta-blockers, calcium channel blockers — how they work and what to expect.',
      keywords: ['blood pressure medication', 'ACE inhibitors', 'beta-blockers', 'amlodipine'],
      learningOutcome: 'Understand how your blood pressure medication works',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 12),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 12),
      url: 'https://cdn.sanctuaryhealth.io/videos/bp-medications.mp4',
      thumbnailUrl: '/thumbnails/bp-medications.jpg',
      durationSeconds: 400,
    }],
  },
  {
    id: id('post', 13),
    universalTitle: 'Diet and Exercise for Blood Pressure',
    contentValue: 86,
    category: ['condition_cardiovascular', 'condition_hypertension', 'wellbeing_nutrition', 'wellbeing_fitness'],
    topic: ['lifestyle'],
    icd10: ['I10'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 13),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Diet and Exercise Changes for Better Blood Pressure',
      description: 'The DASH diet, sodium reduction, exercise recommendations, and other evidence-based lifestyle changes that can meaningfully lower your blood pressure.',
      keywords: ['DASH diet', 'sodium reduction', 'exercise', 'blood pressure lifestyle'],
      learningOutcome: 'Identify diet and exercise changes that lower blood pressure',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 13),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 13),
      url: 'https://cdn.sanctuaryhealth.io/articles/bp-lifestyle.html',
    }],
  },
  {
    id: id('post', 14),
    universalTitle: 'Hypertension Symptoms and Warning Signs',
    contentValue: 84,
    category: ['condition_cardiovascular', 'condition_hypertension'],
    topic: ['symptoms'],
    icd10: ['I10', 'I11'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 14),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Warning Signs You Shouldn\'t Ignore',
      description: 'High blood pressure is often called the "silent killer." Learn what symptoms to watch for and when to seek immediate medical attention.',
      keywords: ['hypertension symptoms', 'headache', 'chest pain', 'emergency signs'],
      learningOutcome: 'Recognise hypertension warning signs requiring medical attention',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 14),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 14),
      url: 'https://cdn.sanctuaryhealth.io/articles/bp-symptoms.html',
    }],
  },
  {
    id: id('post', 15),
    universalTitle: 'Understanding Cardiovascular Risk',
    contentValue: 81,
    category: ['condition_cardiovascular', 'condition_hypertension'],
    topic: ['risks'],
    icd10: ['I10', 'I11'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 15),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Cardiovascular Risks of High Blood Pressure',
      description: 'How uncontrolled high blood pressure affects your heart, arteries, kidneys, and brain — and why consistent management is so important.',
      keywords: ['cardiovascular risk', 'heart disease', 'stroke', 'kidney damage'],
      learningOutcome: 'Understand the long-term risks of uncontrolled hypertension',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 15),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 15),
      url: 'https://cdn.sanctuaryhealth.io/videos/cardiovascular-risk.mp4',
      thumbnailUrl: '/thumbnails/cardiovascular-risk.jpg',
      durationSeconds: 310,
    }],
  },
  {
    id: id('post', 16),
    universalTitle: 'Blood Pressure Medication Side Effects',
    contentValue: 85,
    category: ['condition_cardiovascular', 'condition_hypertension'],
    topic: ['sideEffects'],
    icd10: ['I10'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 16),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Side Effects of Blood Pressure Medication',
      description: 'Common side effects of blood pressure medications, which ones are temporary, and when to talk to your doctor about switching medications.',
      keywords: ['medication side effects', 'dizziness', 'fatigue', 'dry cough'],
      learningOutcome: 'Manage side effects and know when to consult your doctor',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 16),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 16),
      url: 'https://cdn.sanctuaryhealth.io/articles/bp-side-effects.html',
    }],
  },
  {
    id: id('post', 17),
    universalTitle: 'Causes of High Blood Pressure',
    contentValue: 79,
    category: ['condition_cardiovascular', 'condition_hypertension'],
    topic: ['causes'],
    icd10: ['I10'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 17),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'What Causes High Blood Pressure?',
      description: 'Primary vs. secondary hypertension — genetics, salt intake, stress, obesity, and other factors that contribute to elevated blood pressure.',
      keywords: ['hypertension causes', 'salt', 'stress', 'obesity', 'genetics'],
      learningOutcome: 'Understand modifiable and non-modifiable causes of hypertension',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 17),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 17),
      url: 'https://cdn.sanctuaryhealth.io/videos/bp-causes.mp4',
      thumbnailUrl: '/thumbnails/bp-causes.jpg',
      durationSeconds: 270,
    }],
  },
  {
    id: id('post', 18),
    universalTitle: 'Home Blood Pressure Monitoring',
    contentValue: 88,
    category: ['condition_cardiovascular', 'condition_hypertension'],
    topic: ['diagnosis'],
    icd10: ['I10'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 18),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Monitoring Your Blood Pressure at Home',
      description: 'How to correctly take your blood pressure at home, keep a log, and understand what your readings mean for your ongoing care.',
      keywords: ['blood pressure monitor', 'home monitoring', 'readings log'],
      learningOutcome: 'Accurately measure and track blood pressure at home',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 18),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 18),
      url: 'https://cdn.sanctuaryhealth.io/videos/bp-home-monitoring.mp4',
      thumbnailUrl: '/thumbnails/bp-home-monitoring.jpg',
      durationSeconds: 340,
    }],
  },

  // =============================================
  // SCENARIO 3: Generalised Anxiety Disorder (F41.1)
  // =============================================
  {
    id: id('post', 19),
    universalTitle: 'Understanding Anxiety Disorders',
    contentValue: 92,
    category: ['condition_mentalHealth', 'condition_anxiety'],
    topic: ['overview'],
    icd10: ['F41', 'F41.1'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 19),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Understanding Generalised Anxiety Disorder',
      description: 'What generalised anxiety disorder (GAD) is, how it differs from normal worry, and why it is a real medical condition that responds well to treatment.',
      keywords: ['anxiety', 'GAD', 'generalised anxiety', 'mental health'],
      learningOutcome: 'Understand what GAD is and that effective treatments exist',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 19),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 19),
      url: 'https://cdn.sanctuaryhealth.io/videos/anxiety-overview.mp4',
      thumbnailUrl: '/thumbnails/anxiety-overview.jpg',
      durationSeconds: 380,
    }],
  },
  {
    id: id('post', 20),
    universalTitle: 'Anxiety Medication Guide',
    contentValue: 88,
    category: ['condition_mentalHealth', 'condition_anxiety'],
    topic: ['medication'],
    icd10: ['F41', 'F41.1'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 20),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Medications for Anxiety: What to Expect',
      description: 'SSRIs, SNRIs, benzodiazepines — understanding the different medication options for anxiety, how they work, and what the first few weeks are like.',
      keywords: ['anxiety medication', 'SSRIs', 'sertraline', 'benzodiazepines'],
      learningOutcome: 'Understand medication options and set realistic expectations',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 20),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 20),
      url: 'https://cdn.sanctuaryhealth.io/articles/anxiety-medication.html',
    }],
  },
  {
    id: id('post', 21),
    universalTitle: 'Coping Strategies for Anxiety',
    contentValue: 90,
    category: ['condition_mentalHealth', 'condition_anxiety', 'wellbeing_mentalHealth'],
    topic: ['lifestyle'],
    icd10: ['F41', 'F41.1'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 21),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Evidence-Based Coping Strategies',
      description: 'Practical coping techniques backed by research — breathing exercises, grounding techniques, sleep hygiene, and when to use them.',
      keywords: ['coping strategies', 'breathing exercises', 'grounding', 'CBT techniques'],
      learningOutcome: 'Learn 3+ coping techniques you can use immediately',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 21),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 21),
      url: 'https://cdn.sanctuaryhealth.io/videos/anxiety-coping.mp4',
      thumbnailUrl: '/thumbnails/anxiety-coping.jpg',
      durationSeconds: 450,
    }],
  },
  {
    id: id('post', 22),
    universalTitle: 'Recognising Anxiety Symptoms',
    contentValue: 85,
    category: ['condition_mentalHealth', 'condition_anxiety'],
    topic: ['symptoms'],
    icd10: ['F41', 'F41.1'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 22),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Physical and Emotional Symptoms of Anxiety',
      description: 'Anxiety is not just worry — learn about the physical symptoms (racing heart, tension, stomach issues) alongside the emotional ones.',
      keywords: ['anxiety symptoms', 'physical symptoms', 'panic', 'racing thoughts'],
      learningOutcome: 'Recognise both physical and emotional anxiety symptoms',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 22),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 22),
      url: 'https://cdn.sanctuaryhealth.io/articles/anxiety-symptoms.html',
    }],
  },
  {
    id: id('post', 23),
    universalTitle: 'Anxiety Side Effects of Medication',
    contentValue: 83,
    category: ['condition_mentalHealth', 'condition_anxiety'],
    topic: ['sideEffects'],
    icd10: ['F41'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 23),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Managing Side Effects of Anxiety Medication',
      description: 'The first 2-4 weeks on anxiety medication can be challenging. Here is what to expect and when things typically improve.',
      keywords: ['SSRI side effects', 'adjustment period', 'nausea', 'insomnia'],
      learningOutcome: 'Know what to expect in the first weeks and when to seek help',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 23),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 23),
      url: 'https://cdn.sanctuaryhealth.io/articles/anxiety-side-effects.html',
    }],
  },
  {
    id: id('post', 24),
    universalTitle: 'Mental Health Support and Resources',
    contentValue: 87,
    category: ['condition_mentalHealth', 'condition_anxiety', 'wellbeing_mentalHealth'],
    topic: ['support'],
    icd10: ['F41', 'F41.1'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'article',
    postDetailsList: [{
      id: id('pd', 24),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Where to Find Help and Support',
      description: 'Crisis helplines, therapy options (CBT, counselling), support groups, and digital mental health tools available to you.',
      keywords: ['mental health support', 'therapy', 'CBT', 'crisis helpline', 'counselling'],
      learningOutcome: 'Know where to access professional and peer support',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 24),
    }],
    media: [{
      __typename: 'ArticleMedia',
      id: id('am', 24),
      url: 'https://cdn.sanctuaryhealth.io/articles/mental-health-support.html',
    }],
  },
  {
    id: id('post', 25),
    universalTitle: 'What Causes Anxiety Disorders',
    contentValue: 78,
    category: ['condition_mentalHealth', 'condition_anxiety'],
    topic: ['causes'],
    icd10: ['F41', 'F41.1'],
    clinicallyVerified: true,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    mediaType: 'video',
    postDetailsList: [{
      id: id('pd', 25),
      language: 'en',
      languageReviewLevel: 'clinicallyReviewed',
      title: 'Understanding Why Anxiety Develops',
      description: 'The interplay of genetics, brain chemistry, life experiences, and stress in the development of anxiety disorders.',
      keywords: ['anxiety causes', 'genetics', 'stress', 'brain chemistry', 'trauma'],
      learningOutcome: 'Understand that anxiety has biological and environmental causes',
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      postId: id('post', 25),
    }],
    media: [{
      __typename: 'VideoMedia',
      id: id('vm', 25),
      url: 'https://cdn.sanctuaryhealth.io/videos/anxiety-causes.mp4',
      thumbnailUrl: '/thumbnails/anxiety-causes.jpg',
      durationSeconds: 320,
    }],
  },
];
